name: firmaerp_client
description: This FirmaERP repository centralizes the client application and its associated modules.

publish_to: none
homepage: https://firmaerp.softyes.com.br
repository: https://github.com/FirmaERP/firmaerp_client

environment:
  sdk: ^3.10.4
  flutter: ^3.38.5

workspace:
  - app/

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0
