name: firmaerp
description: This FirmaERP repository centralizes the client application and its associated modules.

homepage: https://firmaerp.softyes.com.br
repository: https://github.com/FirmaERP/firmaerp_client

version: 0.1.0+1
publish_to: "none"
resolution: workspace

environment:
  sdk: ^3.10.4
  flutter: ^3.38.5

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  icons_launcher: ^3.0.3

flutter:
  uses-material-design: true
